/**
 * B0 CONTRACTS — `src/contracts/ease.ts`
 *
 * FROZEN. ARCHITECTURE.md §3.3. Pure math, ZERO IMPORTS.
 *
 * The compiler (B3), the metrics module (B9) and the reference-figure builder (B9 Channel B)
 * all use this file, so the easing the critic measures is bit-identical to the easing the
 * compiler baked.
 *
 * This file exports the easing of the project and nothing else. There is no `lerp` on a
 * pose channel anywhere in the codebase (§9.1 A-13, §10). Pelvis yaw is GENERATED by
 * `holdThenSnap`, so a straight ramp has no code path (doc 01 §9.5 fault X3).
 *
 * Derivatives are ANALYTIC. Finite-differencing a baked track to obtain acceleration is
 * forbidden (§1 change 3, §6.3, §9.1 A-2) and grepped by `tools/verify-contracts.mjs`:
 * tangential angular acceleration is identically zero between slerped keys, so a
 * differentiated baked track yields an impulse train instead of one crack.
 */

/** Default end-effector peak-velocity fraction: wrist peak at 73 % of MT. doc 04 §4.3 [MEAS]. */
export const KIME_TAU_PEAK_DEFAULT = 0.73;
/** Default pelvis-yaw hold fraction: koshi no kaiten holds to tau = 0.55. doc 01 §8.3 [TRAD]. */
export const HOLD_UNTIL_DEFAULT = 0.55;

const clamp01 = (x: number): number => (x < 0 ? 0 : x > 1 ? 1 : x);

/** doc 04 §4.2 verbatim. a = tauP / (1 - tauP). */
export const aFromPeak = (tauPeak: number): number => tauPeak / (1 - tauPeak);

/**
 * Normalised progress 0..1 along a technique channel. S(0)=0, S(1)=1, S'(0)=S'(1)=0.
 *
 * doc 04 §4.2:  S(tau) = (a+2)*tau^(a+1) - (a+1)*tau^(a+2)
 *
 * At tauP = 0.73 this is the number that separates karate from mime: 48.6 % of the duration
 * covers the first 20 % of the path and only 18.0 % covers the last 20 % (doc 04 §4.4).
 * Linear spends 20 % on 20 % — a 2.4x error exactly where a trained eye reads.
 */
export function kimeEase(tau: number, tauPeak = KIME_TAU_PEAK_DEFAULT): number {
  const t = clamp01(tau);
  const a = tauPeak / (1 - tauPeak);
  return (a + 2) * Math.pow(t, a + 1) - (a + 1) * Math.pow(t, a + 2);
}

/**
 * Exact normalised speed (mean = 1). Used for analytic cloth/impulse drivers.
 *
 * doc 04 §4.2:  V(tau) = S'(tau) = (a+1)*(a+2)*tau^a*(1-tau)
 * V(0) = V(1) = 0 — the C1 dead stop at the lock. This IS kime.
 * v_peak / v_mean = (a+2)*(a/(a+1))^a  ==  2.009 at tauP = 0.73.
 */
export function kimeEaseVel(tau: number, tauPeak = KIME_TAU_PEAK_DEFAULT): number {
  const t = clamp01(tau);
  const a = tauPeak / (1 - tauPeak);
  return (a + 1) * (a + 2) * Math.pow(t, a) * (1 - t);
}

/**
 * Exact normalised acceleration, d2S/dtau2. THIS is the only legal source of the accel
 * channels (`chan.accelL`, `chan.accelR` — §3.9). Finite-differencing a baked track is
 * forbidden (§6.4, §9.1 A-2).
 *
 * Differentiating V analytically:
 *   S''(tau) = (a+1)*(a+2)*tau^(a-1)*(a - (a+1)*tau)
 *
 * Zero of S'' is at tau = a/(a+1) = tauPeak, as it must be.
 *
 * OUT OF RANGE, tau > 1 or tau < 0: returns 0, NOT the clamped endpoint value. §3.9 evaluates
 * `chan.accelL/accelR` on the whole-kata 480 Hz grid, so tau is outside [0,1] through every hold
 * and every inter-move gap. Clamping tau instead of the value would hold S''(1) = -(a+1)(a+2)
 * = -17.42 forever — a constant phantom brake of ~-75 m/s^2 (7.7 g) on a limb that is at rest —
 * which the cloth wrinkle drive, metric 50 `kime_decel_time_s` and metric 51
 * `accel_profile_skew` would all read as a permanently decelerating wrist. It also removes the
 * `+Infinity` that clamping produced at tau < 0 for tauPeak < 0.5.
 *
 * tau === 1 EXACTLY keeps the one-sided value -(a+1)(a+2): that is the brake AT the lock, the
 * largest-magnitude sample on the curve, and the physical Δv step that `ImpulseEvent` exists to
 * carry. The discontinuity at tau = 1 is kime, not an artefact.
 *
 * NOTE on tau -> 0+ : for tauPeak < 0.5 (a < 1) the exponent a-1 is negative and the true
 * second derivative diverges at the origin; inside [0,1] this function returns that truth rather
 * than a silent lie. The accel channels of §3.9 are wrist channels at tauPeak = 0.73
 * (a = 2.704), and every channel in doc 04 §4.3 that drives an accel* signal has
 * tauPeak >= 0.50, so the divergent branch is unreachable from the shipped channel table.
 */
export function kimeEaseAcc(tau: number, tauPeak = KIME_TAU_PEAK_DEFAULT): number {
  if (tau > 1 || tau < 0) return 0;
  const t = clamp01(tau);
  const a = tauPeak / (1 - tauPeak);
  return (a + 1) * (a + 2) * Math.pow(t, a - 1) * (a - (a + 1) * t);
}

/**
 * doc 01 §8.3 koshi no kaiten: hold to tau=0.55, then 1-(1-u)^3. Linear yaw is unrepresentable.
 *
 * doc 01 §8.3 [TRAD/DERIVED]: psi holds psi_start over t in [0, 0.55]; the rotation window is
 * [0.55, 1.00]; 90 % of the rotation is complete by t = 0.92; 100 % at t = 1.00, coincident
 * with heel contact. Stage S7 asserts the doc 01 §9.5 X3 predicate |psi(0.5) - psi_start| <= 8
 * degrees on every move at compile time — which this function satisfies exactly (it is 0).
 */
export function holdThenSnap(tau: number, holdUntil = HOLD_UNTIL_DEFAULT): number {
  const t = clamp01(tau);
  if (t <= holdUntil) return 0;
  const u = (t - holdUntil) / (1 - holdUntil);
  return 1 - Math.pow(1 - u, 3);
}

/**
 * Exact d/dtau of `holdThenSnap`. The ONLY legal source of `chan.pelvisYawRate` (§3.9,
 * §6.3): that channel is analytic, never finite-differenced from the baked pose.
 *
 * NOT listed in §3.3's signature block, which names only the eight easing functions plus
 * `quatAngleDeg`; added because §6.3 and §9.1 A-2 both require `holdThenSnap'` to exist and
 * B3 "may not define an easing function" (OWNERSHIP B3). Recorded as a deviation.
 */
export function holdThenSnapVel(tau: number, holdUntil = HOLD_UNTIL_DEFAULT): number {
  const t = clamp01(tau);
  if (t <= holdUntil) return 0;
  const span = 1 - holdUntil;
  const u = (t - holdUntil) / span;
  return (3 * Math.pow(1 - u, 2)) / span;
}

/**
 * Closed-form critically damped step response. No integrator, no state.
 * x(t) = 1 - (1 + omega*t) * e^(-omega*t).  doc 06 §6.5 head spring: omega = 14 rad/s, zeta = 1.
 */
export function criticalDampClosed(t: number, omega: number): number {
  if (t <= 0) return 0;
  const wt = omega * t;
  return 1 - (1 + wt) * Math.exp(-wt);
}

/**
 * Closed-form second-order settle, doc 04 §5.1. Returns a signed offset multiplier.
 * x(t) = e^(-zeta*omegaN*t) * sin(omegaN*sqrt(1-zeta^2)*t), amplitude A = 1.
 * First overshoot M_p = e^(-pi*zeta/sqrt(1-zeta^2)); zeta 0.40 -> 0.254, i.e. one clearly
 * readable bounce (doc 04 §5.1).
 *
 * zeta >= 1 is the ANALYTIC CONTINUATION of that same formula, not a second model:
 * sin(i*x) = i*sinh(x), so the damped frequency `omegaN*sqrt(1-zeta^2)` continues to
 * `omegaN*sqrt(zeta^2-1)` under sinh. It is CONTINUOUS at zeta = 1, where both branches go to 0
 * — because with doc 04's amplitude-1-SINE normalisation the oscillatory term vanishes at
 * critical damping, so the offset really is identically zero there.
 *
 * The previous form, `omegaN*t*e^(1-omegaN*t)`, was an invented unit-peak normalisation and made
 * the function discontinuous by 61x at zeta = 1 (peak 0.0165 at zeta 0.999, 1.0000 at zeta 1.0)
 * while ignoring zeta entirely above 1. §4.8's `ui/look.ts` exposes live knobs, so a slider that
 * reached zeta = 1 would have read as a solver blow-up rather than a branch seam.
 *
 * doc 04 §5.1's own zeta values top out at 0.55 + 0.10 = 0.65 (`SETTLE_ZETA_MAX`); the zeta >= 1
 * branch is a guard against an out-of-band knob, never a modelled regime. B8 clamps the GUI to
 * [0.05, SETTLE_ZETA_MAX] and B1 never authors zeta >= 1.
 */
export const SETTLE_ZETA_MAX = 0.65 as const;   // doc 04 §5.1: max row is 0.55 +- 0.10

export function settle2(t: number, omegaN: number, zeta: number): number {
  if (t <= 0) return 0;
  if (zeta >= 1) {
    const wdHyp = omegaN * Math.sqrt(zeta * zeta - 1);
    return Math.exp(-zeta * omegaN * t) * Math.sinh(wdHyp * t);
  }
  const wd = omegaN * Math.sqrt(1 - zeta * zeta);
  return Math.exp(-zeta * omegaN * t) * Math.sin(wd * t);
}

/** First-overshoot ratio of `settle2`, doc 04 §5.1. zeta 0.30 -> 0.372, 0.40 -> 0.254. */
export const overshootRatio = (zeta: number): number =>
  zeta >= 1 ? 0 : Math.exp((-Math.PI * zeta) / Math.sqrt(1 - zeta * zeta));

export const easeOutCubic = (u: number): number => 1 - Math.pow(1 - clamp01(u), 3);

/** Standard ease-in-out cubic. UI/camera blends only — never a pose channel. */
export const easeInOutCubic = (u: number): number => {
  const t = clamp01(u);
  return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
};

/**
 * Geodesic angle between two unit quaternions, degrees. Used by the baker and its gate
 * (G-9a `maxSlerpErrDeg`, G-9b `maxStepDeg`). Sign-insensitive: q and -q are the same
 * rotation, so the double cover is folded with `abs`.
 */
export function quatAngleDeg(
  ax: number, ay: number, az: number, aw: number,
  bx: number, by: number, bz: number, bw: number,
): number {
  let d = ax * bx + ay * by + az * bz + aw * bw;
  d = d < 0 ? -d : d;
  if (d > 1) d = 1;
  return 2 * Math.acos(d) * (180 / Math.PI);
}
